spring.application.name=wigell-autocore

spring.datasource.url=jdbc:mysql://localhost:3306/wigell_autocore_db
spring.datasource.username= root
spring.datasource.password=techtjej2026
spring.jpa.hibernate.ddl-auto=update

# Visa SQL-frågor från Hibernate (bra vid felsökning)
spring.jpa.show-sql=true

# Sätt loggnivå för ditt eget projekt till DEBUG (visar alla logger.debug-anrop)
logging.level.com.wac.autocore=DEBUG

# Sätt loggnivå för Hibernate om du vill se detaljer kring databasanrop
logging.level.org.hibernate.SQL=DEBUG